export const content: object = {
  title: 'Mozilla’s Next Chapter',
  hash: '#mozillas-next-chapter',
  author: {
    name: 'Mark Surman',
    job_title: 'Executive Director, Mozilla Foundation',
    image: '/public/headshot.png',
  },
  lead_article: true,
  excerpt: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec augue turpis.',
  body: '<h3>Significant changes in our world — shifts in public opinion, public policy and products — often seem to happen organically, as if they were destined.</h3><p>Yet, those of us who devote our time or careers to advocacy know that’s not exactly how things unfold. Of course, there is an element of spontaneity to any movement — a stark moment of injustice or outrage that propels an issue into the zeitgeist, creating a groundswell of support. But, more commonly, a groundswell for change is developed through many years of research, community building and organizing that creates — and sustains — the momentum for change.</p><p>At Mozilla, this latter part of advocacy — the research, community building and organizing — is core to our work. This approach is true to the values of open source, but applied in a different domain. Rather than gathering code contributions, we’re gathering data and opinions from global communities online to help us understand — and change — the products we all use. Like in open source, the scale and diversity of contributors is core to creating the value. We can only accurately “see” into tech platforms when we generate contributions from thousands of people around the world. We can only build ethical voice data sets to innovators if we include underserved languages of the world.</p><h4>Collaborative, open source approach</h4><p>This collaborative, open source approach was integral to Mozilla’s advocacy successes in 2022. Mozilla advocacy around YouTube’s opaque recommendation AI is a prime example. For years, the algorithm has polarized and radicalized users. And YouTube has refused to provide transparency into the system. So we continued work with our RegretsReporter community: tens of thousands of YouTube users who have downloaded Mozilla’s browser extension and answered the call to become citizen scientists. This community donated their data, answered our interview questions, and more. And together, we determined that YouTube’s algorithmic controls don’t work as intended. As a result, the movement of people upset about YouTube’s AI grew and became more engaged — and YouTube publicly acknowledged their UI controls need fixing.</p><p>Mozilla Common Voice is another example of advocacy through community. There’s a desperate need for more diverse voice data sets — currently, Siri, Alexa, and Google Assistant don’t support a single native African language. Mozilla has been advocating for this diversity — and like we did with YouTube, we didn’t go it alone. Through Common Voice, we’re collecting voice data in a range of underserved languages, and then making it open source. In September, we hit a major milestone: 100 languages in the Common Voice dataset. We’re advocating for better voice technology not just with our words, but with the words of others — quite literally.</p>'
};
