export const content: object = {
  title: 'Why I work for Mozilla',
  tag: 'choose',
  hash: '#Leyla-Samiee',
  author: {
    name: 'Leyla Samiee',
    job_title: 'VP of Engineering - Mozilla Social',
    image: '/headshots/Leyla-Samiee.jpeg',
  },
  lead_article: true,
  modal_style: 'short',
  excerpt: 'Carlos Torres joined the team in August as Chief Legal Officer.',
  body: '<p>Mozilla has been an oddly nostalgic dream come true– The Netscape days and the UNIX world were the start of my career. My involvement with the GNU project started early and allowed me to witness the power of collaboration and shared knowledge. I fondly recall the days when the internet was characterized by its freedom, purity of information, and joy of discovery.</p><p>Within the past decade, society has found that all that glitters is not, unfortunately, gold– we’ve seen this represented in the rise of polarization, promoting hatred, manipulated facts, and the exclusion or targeting of groups. As my passion for human-centric technology has rapidly grown amidst these challenges, Mozilla has provided a beacon of hope for me with its pioneering spirit.</p><p>Joining Mozilla has been my next step towards my hopes of restoring the internet’s fundamental principles on the human experience. Web 1.0 was the world’s dominant information systems platform, and it fulfilled equality, empowering people, uniting communities worldwide, providing knowledge, and so much more. Mozilla wants respectful conversation, the understanding of human dignity, and the encouragement of personal expression– my morals line up perfectly with these ideals. My decision to work at Mozilla with the focus on building an alternative in social space, is deeply rooted in an overwhelming commitment to preserving and enhancing the values that an open, global internet would ideally represent.</p><p>I am excited to join the team, and to embrace the concept of distributed social networks., I feel as though the team at Mozilla are more than poised to reshape the internet landscape, and to give individuals the ability to customize their interactive experiences. We hope to do so by placing trust and safety at the center of everything we do to heal the rifts on the internet. We envision an internet where authenticity reigns, misinformation dissolves, and individuals can navigate the digital sphere with confidence. The under-represented should gain power and equality in their voices, ideas and presence on the net.</p><p>In this transformative journey, I am driven by the belief that we can reclaim the internet’s essence— a space where safety, joy, and the purity of information exists. At Mozilla, I have found a community of like-minded individuals, united by a shared vision of a better internet. My choice to work at Mozilla is not merely a career decision; it is a heartfelt commitment to shaping a future where the internet reflects our noblest aspirations. In this pursuit, I have found purpose, passion, and a profound sense of responsibility—an unwavering dedication to ushering in a new era of digital enlightenment.</p>'
};
