export const content: object = {
  title: 'Why I work for Mozilla',
  tag: 'choose',
  hash: '#sulafa-said-silim',
  author: {
    name: 'Sulafa Said-Silim',
    job_title: 'Sr. Advisor, Diversity Equity Inclusion & Belonging',
    image: '/headshots/Sulafa-Said-Silim.jpeg',
  },
  lead_article: true,
  modal_style: 'medium',
  excerpt: '“Mozilla’s work is deeply connected to social impact and social wellbeing of marginalized - it is rooted in the integration in elevating voices of the voiceless and showcasing that you can be both responsible and fiscally ambitious”',
  body: '<p>In my current role as the leader of DEIB (Diversity, Equity, Inclusion, and Belonging) at the Mozilla Foundation, I am dedicated to promoting harm awareness and creating a harm-reductive environment. My decision to join Mozilla was founded on the principle of nurturing inclusive digital champions, dedicated to building a world characterized by trustworthy AI and supporting marginalized digital communities through continuous learning and growth. At Mozilla, we are committed to experimentation, embracing growth, and refining our strategies in the ever-evolving digital landscape.</p><p>My journey began in multimedia journalism, where I recognized the inextricable link between technology and journalism. This path led me to work with UN agencies and international organizations across Africa, Asia, and Europe. One pivotal role was with the Bill & Melinda Gates Foundation’s AWARD Fellowship, the inaugural African-wide human capacity building program. In these roles, I focused on enhancing communication strategies and capacity-building initiatives, with a strong emphasis on social inclusivity and impact. Notably, I co-created educational tools with youth in the UK as part of the groundbreaking Digital Disruption project, addressing digital propaganda and misinformation related to radicalization.</p><p>Mozilla’s work is deeply connected to the social impact and wellbeing of marginalized communities. It is rooted in elevating the voices of the voiceless and showcasing that you can be both responsible and fiscally ambitious.</p><p>In 2018, I founded Dawa Apothecary, a borderless health and wellness platform dedicated to empowering women of color. My vision centers on amplifying the voices of marginalized individuals, both professionally and within the sanctuary of their homes. This work earned me recognition on the ’How I Made It’ list of the top 50 millennial women to watch in Canada.</p><p>Before joining Mozilla, I assumed the role of Diversity, Equity, and Inclusion (DEI) and Culture leader at Weston Foods, where I created a psychologically safe and equitable workplace environment across the United States and Canada. I am deeply committed to the power of storytelling in fostering connections, bridging gaps, and building equitable workplaces.</p>`'
};
